upperband, middleband, lowerband = BBANDS(close, timeperiod=5, nbdevup=2, nbdevdn=2, matype=0)
real = DEMA(close, timeperiod=30)
real = EMA(close, timeperiod=30)
real = HT_TRENDLINE(close)
real = KAMA(close, timeperiod=30)
real = MA(close, timeperiod=30, matype=0)
mama, fama = MAMA(close, fastlimit=0, slowlimit=0)
real = MAVP(close, periods, minperiod=2, maxperiod=30, matype=0)
real = MIDPOINT(close, timeperiod=14)
real = MIDPRICE(high, low, timeperiod=14)
real = SAR(high, low, acceleration=0, maximum=0)
real = SAREXT(high, low, startvalue=0, offsetonreverse=0, accelerationinitlong=0, accelerationlong=0, accelerationmaxlong=0, accelerationinitshort=0, accelerationshort=0, accelerationmaxshort=0)
real = SMA(close, timeperiod=30)
real = T3(close, timeperiod=5, vfactor=0)
real = TEMA(close, timeperiod=30)
real = TRIMA(close, timeperiod=30)
real = WMA(close, timeperiod=30)
real = ADX(high, low, close, timeperiod=14)
real = ADXR(high, low, close, timeperiod=14)
real = APO(close, fastperiod=12, slowperiod=26, matype=0)
aroondown, aroonup = AROON(high, low, timeperiod=14)
real = AROONOSC(high, low, timeperiod=14)
real = BOP(open, high, low, close)
real = CCI(high, low, close, timeperiod=14)
real = CMO(close, timeperiod=14)
real = DX(high, low, close, timeperiod=14)
macd, macdsignal, macdhist = MACD(close, fastperiod=12, slowperiod=26, signalperiod=9)
macd, macdsignal, macdhist = MACDEXT(close, fastperiod=12, fastmatype=0, slowperiod=26, slowmatype=0, signalperiod=9, signalmatype=0)
macd, macdsignal, macdhist = MACDFIX(close, signalperiod=9)
real = MFI(high, low, close, volume, timeperiod=14)
real = MINUS_DI(high, low, close, timeperiod=14)
real = MINUS_DM(high, low, timeperiod=14)
real = MOM(close, timeperiod=10)
real = PLUS_DI(high, low, close, timeperiod=14)
real = PLUS_DM(high, low, timeperiod=14)
real = PPO(close, fastperiod=12, slowperiod=26, matype=0)
real = ROC(close, timeperiod=10)
real = ROCP(close, timeperiod=10)
real = ROCR(close, timeperiod=10)
real = ROCR100(close, timeperiod=10)
real = RSI(close, timeperiod=14)
slowk, slowd = STOCH(high, low, close, fastk_period=5, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)
fastk, fastd = STOCHF(high, low, close, fastk_period=5, fastd_period=3, fastd_matype=0)
fastk, fastd = STOCHRSI(close, timeperiod=14, fastk_period=5, fastd_period=3, fastd_matype=0)
real = TRIX(close, timeperiod=30)
real = ULTOSC(high, low, close, timeperiod1=7, timeperiod2=14, timeperiod3=28)
real = WILLR(high, low, close, timeperiod=14)
real = AD(high, low, close, volume)
real = ADOSC(high, low, close, volume, fastperiod=3, slowperiod=10)
real = OBV(close, volume)
real = ATR(high, low, close, timeperiod=14)
real = NATR(high, low, close, timeperiod=14)
real = TRANGE(high, low, close)
real = AVGPRICE(open, high, low, close)
real = MEDPRICE(high, low)
real = TYPPRICE(high, low, close)
real = WCLPRICE(high, low, close)
real = HT_DCPERIOD(close)
real = HT_DCPHASE(close)
inphase, quadrature = HT_PHASOR(close)
sine, leadsine = HT_SINE(close)
integer = HT_TRENDMODE(close)
integer = CDL2CROWS(open, high, low, close)
integer = CDL3BLACKCROWS(open, high, low, close)
integer = CDL3INSIDE(open, high, low, close)
integer = CDL3LINESTRIKE(open, high, low, close)
integer = CDL3OUTSIDE(open, high, low, close)
integer = CDL3STARSINSOUTH(open, high, low, close)
integer = CDL3WHITESOLDIERS(open, high, low, close)
integer = CDLABANDONEDBABY(open, high, low, close, penetration=0)
integer = CDLADVANCEBLOCK(open, high, low, close)
integer = CDLBELTHOLD(open, high, low, close)
integer = CDLBREAKAWAY(open, high, low, close)
integer = CDLCLOSINGMARUBOZU(open, high, low, close)
integer = CDLCONCEALBABYSWALL(open, high, low, close)
integer = CDLCOUNTERATTACK(open, high, low, close)
integer = CDLDARKCLOUDCOVER(open, high, low, close, penetration=0)
integer = CDLDOJI(open, high, low, close)
integer = CDLDOJISTAR(open, high, low, close)
integer = CDLDRAGONFLYDOJI(open, high, low, close)
integer = CDLENGULFING(open, high, low, close)
integer = CDLEVENINGDOJISTAR(open, high, low, close, penetration=0)
integer = CDLEVENINGSTAR(open, high, low, close, penetration=0)
integer = CDLGAPSIDESIDEWHITE(open, high, low, close)
integer = CDLGRAVESTONEDOJI(open, high, low, close)
integer = CDLHAMMER(open, high, low, close)
integer = CDLHANGINGMAN(open, high, low, close)
integer = CDLHARAMI(open, high, low, close)
integer = CDLHARAMICROSS(open, high, low, close)
integer = CDLHIGHWAVE(open, high, low, close)
integer = CDLHIKKAKE(open, high, low, close)
integer = CDLHIKKAKEMOD(open, high, low, close)
integer = CDLHOMINGPIGEON(open, high, low, close)
integer = CDLIDENTICAL3CROWS(open, high, low, close)
integer = CDLINNECK(open, high, low, close)
integer = CDLINVERTEDHAMMER(open, high, low, close)
integer = CDLKICKING(open, high, low, close)
integer = CDLKICKINGBYLENGTH(open, high, low, close)
integer = CDLLADDERBOTTOM(open, high, low, close)
integer = CDLLONGLEGGEDDOJI(open, high, low, close)
integer = CDLLONGLINE(open, high, low, close)
integer = CDLMARUBOZU(open, high, low, close)
integer = CDLMATCHINGLOW(open, high, low, close)
integer = CDLMATHOLD(open, high, low, close, penetration=0)
integer = CDLMORNINGDOJISTAR(open, high, low, close, penetration=0)
integer = CDLMORNINGSTAR(open, high, low, close, penetration=0)
integer = CDLONNECK(open, high, low, close)
integer = CDLPIERCING(open, high, low, close)
integer = CDLRICKSHAWMAN(open, high, low, close)
integer = CDLRISEFALL3METHODS(open, high, low, close)
integer = CDLSEPARATINGLINES(open, high, low, close)
integer = CDLSHOOTINGSTAR(open, high, low, close)
integer = CDLSHORTLINE(open, high, low, close)
integer = CDLSPINNINGTOP(open, high, low, close)
integer = CDLSTALLEDPATTERN(open, high, low, close)
integer = CDLSTICKSANDWICH(open, high, low, close)
integer = CDLTAKURI(open, high, low, close)
integer = CDLTASUKIGAP(open, high, low, close)
integer = CDLTHRUSTING(open, high, low, close)
integer = CDLTRISTAR(open, high, low, close)
integer = CDLUNIQUE3RIVER(open, high, low, close)
integer = CDLUPSIDEGAP2CROWS(open, high, low, close)
integer = CDLXSIDEGAP3METHODS(open, high, low, close)
real = BETA(high, low, timeperiod=5)
real = CORREL(high, low, timeperiod=30)
real = LINEARREG(close, timeperiod=14)
real = LINEARREG_ANGLE(close, timeperiod=14)
real = LINEARREG_INTERCEPT(close, timeperiod=14)
real = LINEARREG_SLOPE(close, timeperiod=14)
real = STDDEV(close, timeperiod=5, nbdev=1)
real = TSF(close, timeperiod=14)
real = VAR(close, timeperiod=5, nbdev=1)
real = ACOS(close)
real = ASIN(close)
real = ATAN(close)
real = CEIL(close)
real = COS(close)
real = COSH(close)
real = EXP(close)
real = FLOOR(close)
real = LN(close)
real = LOG10(close)
real = SIN(close)
real = SINH(close)
real = SQRT(close)
real = TAN(close)
real = TANH(close)
real = ADD(high, low)
real = DIV(high, low)
real = MAX(close, timeperiod=30)
integer = MAXINDEX(close, timeperiod=30)
real = MIN(close, timeperiod=30)
integer = MININDEX(close, timeperiod=30)
min, max = MINMAX(close, timeperiod=30)
minidx, maxidx = MINMAXINDEX(close, timeperiod=30)
real = MULT(high, low)
real = SUB(high, low)
real = SUM(close, timeperiod=30)
