,
'upperband, middleband, lowerband = BBANDS(close, timeperiod=5, nbdevup=2, nbdevdn=2, matype=0)',
'DEMA' : 'df["DEMA"] =  DEMA(close, timeperiod=30)',
'EMA' : 'df["EMA"] =  EMA(close, timeperiod=30)',
'HT_TRENDLINE' : 'df["HT_TRENDLINE"] =  HT_TRENDLINE(close)',
'KAMA' : 'df["KAMA"] =  KAMA(close, timeperiod=30)',
'MA' : 'df["MA"] =  MA(close, timeperiod=30, matype=0)',
'mama, fama = MAMA(close, fastlimit=0, slowlimit=0)',
'MAVP' : 'df["MAVP"] =  MAVP(close, periods, minperiod=2, maxperiod=30, matype=0)',
'MIDPOINT' : 'df["MIDPOINT"] =  MIDPOINT(close, timeperiod=14)',
'MIDPRICE' : 'df["MIDPRICE"] =  MIDPRICE(high, low, timeperiod=14)',
'SAR' : 'df["SAR"] =  SAR(high, low, acceleration=0, maximum=0)',
'SAREXT' : 'df["SAREXT"] =  SAREXT(high, low, startvalue=0, offsetonreverse=0, accelerationinitlong=0, accelerationlong=0, accelerationmaxlong=0, accelerationinitshort=0, accelerationshort=0, accelerationmaxshort=0)',
'SMA' : 'df["SMA"] =  SMA(close, timeperiod=30)',
'T3' : 'df["T3"] =  T3(close, timeperiod=5, vfactor=0)',
'TEMA' : 'df["TEMA"] =  TEMA(close, timeperiod=30)',
'TRIMA' : 'df["TRIMA"] =  TRIMA(close, timeperiod=30)',
'WMA' : 'df["WMA"] =  WMA(close, timeperiod=30)',
'ADX' : 'df["ADX"] =  ADX(high, low, close, timeperiod=14)',
'ADXR' : 'df["ADXR"] =  ADXR(high, low, close, timeperiod=14)',
'APO' : 'df["APO"] =  APO(close, fastperiod=12, slowperiod=26, matype=0)',
'aroondown, aroonup = AROON(high, low, timeperiod=14)',
'AROONOSC' : 'df["AROONOSC"] =  AROONOSC(high, low, timeperiod=14)',
'BOP' : 'df["BOP"] =  BOP(open, high, low, close)',
'CCI' : 'df["CCI"] =  CCI(high, low, close, timeperiod=14)',
'CMO' : 'df["CMO"] =  CMO(close, timeperiod=14)',
'DX' : 'df["DX"] =  DX(high, low, close, timeperiod=14)',
'macd, macdsignal, macdhist = MACD(close, fastperiod=12, slowperiod=26, signalperiod=9)',
'macd, macdsignal, macdhist = MACDEXT(close, fastperiod=12, fastmatype=0, slowperiod=26, slowmatype=0, signalperiod=9, signalmatype=0)',
'macd, macdsignal, macdhist = MACDFIX(close, signalperiod=9)',
'MFI' : 'df["MFI"] =  MFI(high, low, close, volume, timeperiod=14)',
'MINUS_DI' : 'df["MINUS_DI"] =  MINUS_DI(high, low, close, timeperiod=14)',
'MINUS_DM' : 'df["MINUS_DM"] =  MINUS_DM(high, low, timeperiod=14)',
'MOM' : 'df["MOM"] =  MOM(close, timeperiod=10)',
'PLUS_DI' : 'df["PLUS_DI"] =  PLUS_DI(high, low, close, timeperiod=14)',
'PLUS_DM' : 'df["PLUS_DM"] =  PLUS_DM(high, low, timeperiod=14)',
'PPO' : 'df["PPO"] =  PPO(close, fastperiod=12, slowperiod=26, matype=0)',
'ROC' : 'df["ROC"] =  ROC(close, timeperiod=10)',
'ROCP' : 'df["ROCP"] =  ROCP(close, timeperiod=10)',
'ROCR' : 'df["ROCR"] =  ROCR(close, timeperiod=10)',
'ROCR100' : 'df["ROCR100"] =  ROCR100(close, timeperiod=10)',
'RSI' : 'df["RSI"] =  RSI(close, timeperiod=14)',
'slowk, slowd = STOCH(high, low, close, fastk_period=5, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)',
'fastk, fastd = STOCHF(high, low, close, fastk_period=5, fastd_period=3, fastd_matype=0)',
'fastk, fastd = STOCHRSI(close, timeperiod=14, fastk_period=5, fastd_period=3, fastd_matype=0)',
'TRIX' : 'df["TRIX"] =  TRIX(close, timeperiod=30)',
'ULTOSC' : 'df["ULTOSC"] =  ULTOSC(high, low, close, timeperiod1=7, timeperiod2=14, timeperiod3=28)',
'WILLR' : 'df["WILLR"] =  WILLR(high, low, close, timeperiod=14)',
'AD' : 'df["AD"] =  AD(high, low, close, volume)',
'ADOSC' : 'df["ADOSC"] =  ADOSC(high, low, close, volume, fastperiod=3, slowperiod=10)',
'OBV' : 'df["OBV"] =  OBV(close, volume)',
'ATR' : 'df["ATR"] =  ATR(high, low, close, timeperiod=14)',
'NATR' : 'df["NATR"] =  NATR(high, low, close, timeperiod=14)',
'TRANGE' : 'df["TRANGE"] =  TRANGE(high, low, close)',
'AVGPRICE' : 'df["AVGPRICE"] =  AVGPRICE(open, high, low, close)',
'MEDPRICE' : 'df["MEDPRICE"] =  MEDPRICE(high, low)',
'TYPPRICE' : 'df["TYPPRICE"] =  TYPPRICE(high, low, close)',
'WCLPRICE' : 'df["WCLPRICE"] =  WCLPRICE(high, low, close)',
'HT_DCPERIOD' : 'df["HT_DCPERIOD"] =  HT_DCPERIOD(close)',
'HT_DCPHASE' : 'df["HT_DCPHASE"] =  HT_DCPHASE(close)',
'inphase, quadrature = HT_PHASOR(close)',
'sine, leadsine = HT_SINE(close)',
'HT_TRENDMODE' : 'df["HT_TRENDMODE"] =  HT_TRENDMODE(close)',
'CDL2CROWS' : 'df["CDL2CROWS"] =  CDL2CROWS(open, high, low, close)',
'CDL3BLACKCROWS' : 'df["CDL3BLACKCROWS"] =  CDL3BLACKCROWS(open, high, low, close)',
'CDL3INSIDE' : 'df["CDL3INSIDE"] =  CDL3INSIDE(open, high, low, close)',
'CDL3LINESTRIKE' : 'df["CDL3LINESTRIKE"] =  CDL3LINESTRIKE(open, high, low, close)',
'CDL3OUTSIDE' : 'df["CDL3OUTSIDE"] =  CDL3OUTSIDE(open, high, low, close)',
'CDL3STARSINSOUTH' : 'df["CDL3STARSINSOUTH"] =  CDL3STARSINSOUTH(open, high, low, close)',
'CDL3WHITESOLDIERS' : 'df["CDL3WHITESOLDIERS"] =  CDL3WHITESOLDIERS(open, high, low, close)',
'CDLABANDONEDBABY' : 'df["CDLABANDONEDBABY"] =  CDLABANDONEDBABY(open, high, low, close, penetration=0)',
'CDLADVANCEBLOCK' : 'df["CDLADVANCEBLOCK"] =  CDLADVANCEBLOCK(open, high, low, close)',
'CDLBELTHOLD' : 'df["CDLBELTHOLD"] =  CDLBELTHOLD(open, high, low, close)',
'CDLBREAKAWAY' : 'df["CDLBREAKAWAY"] =  CDLBREAKAWAY(open, high, low, close)',
'CDLCLOSINGMARUBOZU' : 'df["CDLCLOSINGMARUBOZU"] =  CDLCLOSINGMARUBOZU(open, high, low, close)',
'CDLCONCEALBABYSWALL' : 'df["CDLCONCEALBABYSWALL"] =  CDLCONCEALBABYSWALL(open, high, low, close)',
'CDLCOUNTERATTACK' : 'df["CDLCOUNTERATTACK"] =  CDLCOUNTERATTACK(open, high, low, close)',
'CDLDARKCLOUDCOVER' : 'df["CDLDARKCLOUDCOVER"] =  CDLDARKCLOUDCOVER(open, high, low, close, penetration=0)',
'CDLDOJI' : 'df["CDLDOJI"] =  CDLDOJI(open, high, low, close)',
'CDLDOJISTAR' : 'df["CDLDOJISTAR"] =  CDLDOJISTAR(open, high, low, close)',
'CDLDRAGONFLYDOJI' : 'df["CDLDRAGONFLYDOJI"] =  CDLDRAGONFLYDOJI(open, high, low, close)',
'CDLENGULFING' : 'df["CDLENGULFING"] =  CDLENGULFING(open, high, low, close)',
'CDLEVENINGDOJISTAR' : 'df["CDLEVENINGDOJISTAR"] =  CDLEVENINGDOJISTAR(open, high, low, close, penetration=0)',
'CDLEVENINGSTAR' : 'df["CDLEVENINGSTAR"] =  CDLEVENINGSTAR(open, high, low, close, penetration=0)',
'CDLGAPSIDESIDEWHITE' : 'df["CDLGAPSIDESIDEWHITE"] =  CDLGAPSIDESIDEWHITE(open, high, low, close)',
'CDLGRAVESTONEDOJI' : 'df["CDLGRAVESTONEDOJI"] =  CDLGRAVESTONEDOJI(open, high, low, close)',
'CDLHAMMER' : 'df["CDLHAMMER"] =  CDLHAMMER(open, high, low, close)',
'CDLHANGINGMAN' : 'df["CDLHANGINGMAN"] =  CDLHANGINGMAN(open, high, low, close)',
'CDLHARAMI' : 'df["CDLHARAMI"] =  CDLHARAMI(open, high, low, close)',
'CDLHARAMICROSS' : 'df["CDLHARAMICROSS"] =  CDLHARAMICROSS(open, high, low, close)',
'CDLHIGHWAVE' : 'df["CDLHIGHWAVE"] =  CDLHIGHWAVE(open, high, low, close)',
'CDLHIKKAKE' : 'df["CDLHIKKAKE"] =  CDLHIKKAKE(open, high, low, close)',
'CDLHIKKAKEMOD' : 'df["CDLHIKKAKEMOD"] =  CDLHIKKAKEMOD(open, high, low, close)',
'CDLHOMINGPIGEON' : 'df["CDLHOMINGPIGEON"] =  CDLHOMINGPIGEON(open, high, low, close)',
'CDLIDENTICAL3CROWS' : 'df["CDLIDENTICAL3CROWS"] =  CDLIDENTICAL3CROWS(open, high, low, close)',
'CDLINNECK' : 'df["CDLINNECK"] =  CDLINNECK(open, high, low, close)',
'CDLINVERTEDHAMMER' : 'df["CDLINVERTEDHAMMER"] =  CDLINVERTEDHAMMER(open, high, low, close)',
'CDLKICKING' : 'df["CDLKICKING"] =  CDLKICKING(open, high, low, close)',
'CDLKICKINGBYLENGTH' : 'df["CDLKICKINGBYLENGTH"] =  CDLKICKINGBYLENGTH(open, high, low, close)',
'CDLLADDERBOTTOM' : 'df["CDLLADDERBOTTOM"] =  CDLLADDERBOTTOM(open, high, low, close)',
'CDLLONGLEGGEDDOJI' : 'df["CDLLONGLEGGEDDOJI"] =  CDLLONGLEGGEDDOJI(open, high, low, close)',
'CDLLONGLINE' : 'df["CDLLONGLINE"] =  CDLLONGLINE(open, high, low, close)',
'CDLMARUBOZU' : 'df["CDLMARUBOZU"] =  CDLMARUBOZU(open, high, low, close)',
'CDLMATCHINGLOW' : 'df["CDLMATCHINGLOW"] =  CDLMATCHINGLOW(open, high, low, close)',
'CDLMATHOLD' : 'df["CDLMATHOLD"] =  CDLMATHOLD(open, high, low, close, penetration=0)',
'CDLMORNINGDOJISTAR' : 'df["CDLMORNINGDOJISTAR"] =  CDLMORNINGDOJISTAR(open, high, low, close, penetration=0)',
'CDLMORNINGSTAR' : 'df["CDLMORNINGSTAR"] =  CDLMORNINGSTAR(open, high, low, close, penetration=0)',
'CDLONNECK' : 'df["CDLONNECK"] =  CDLONNECK(open, high, low, close)',
'CDLPIERCING' : 'df["CDLPIERCING"] =  CDLPIERCING(open, high, low, close)',
'CDLRICKSHAWMAN' : 'df["CDLRICKSHAWMAN"] =  CDLRICKSHAWMAN(open, high, low, close)',
'CDLRISEFALL3METHODS' : 'df["CDLRISEFALL3METHODS"] =  CDLRISEFALL3METHODS(open, high, low, close)',
'CDLSEPARATINGLINES' : 'df["CDLSEPARATINGLINES"] =  CDLSEPARATINGLINES(open, high, low, close)',
'CDLSHOOTINGSTAR' : 'df["CDLSHOOTINGSTAR"] =  CDLSHOOTINGSTAR(open, high, low, close)',
'CDLSHORTLINE' : 'df["CDLSHORTLINE"] =  CDLSHORTLINE(open, high, low, close)',
'CDLSPINNINGTOP' : 'df["CDLSPINNINGTOP"] =  CDLSPINNINGTOP(open, high, low, close)',
'CDLSTALLEDPATTERN' : 'df["CDLSTALLEDPATTERN"] =  CDLSTALLEDPATTERN(open, high, low, close)',
'CDLSTICKSANDWICH' : 'df["CDLSTICKSANDWICH"] =  CDLSTICKSANDWICH(open, high, low, close)',
'CDLTAKURI' : 'df["CDLTAKURI"] =  CDLTAKURI(open, high, low, close)',
'CDLTASUKIGAP' : 'df["CDLTASUKIGAP"] =  CDLTASUKIGAP(open, high, low, close)',
'CDLTHRUSTING' : 'df["CDLTHRUSTING"] =  CDLTHRUSTING(open, high, low, close)',
'CDLTRISTAR' : 'df["CDLTRISTAR"] =  CDLTRISTAR(open, high, low, close)',
'CDLUNIQUE3RIVER' : 'df["CDLUNIQUE3RIVER"] =  CDLUNIQUE3RIVER(open, high, low, close)',
'CDLUPSIDEGAP2CROWS' : 'df["CDLUPSIDEGAP2CROWS"] =  CDLUPSIDEGAP2CROWS(open, high, low, close)',
'CDLXSIDEGAP3METHODS' : 'df["CDLXSIDEGAP3METHODS"] =  CDLXSIDEGAP3METHODS(open, high, low, close)',
'BETA' : 'df["BETA"] =  BETA(high, low, timeperiod=5)',
'CORREL' : 'df["CORREL"] =  CORREL(high, low, timeperiod=30)',
'LINEARREG' : 'df["LINEARREG"] =  LINEARREG(close, timeperiod=14)',
'LINEARREG_ANGLE' : 'df["LINEARREG_ANGLE"] =  LINEARREG_ANGLE(close, timeperiod=14)',
'LINEARREG_INTERCEPT' : 'df["LINEARREG_INTERCEPT"] =  LINEARREG_INTERCEPT(close, timeperiod=14)',
'LINEARREG_SLOPE' : 'df["LINEARREG_SLOPE"] =  LINEARREG_SLOPE(close, timeperiod=14)',
'STDDEV' : 'df["STDDEV"] =  STDDEV(close, timeperiod=5, nbdev=1)',
'TSF' : 'df["TSF"] =  TSF(close, timeperiod=14)',
'VAR' : 'df["VAR"] =  VAR(close, timeperiod=5, nbdev=1)',
'ACOS' : 'df["ACOS"] =  ACOS(close)',
'ASIN' : 'df["ASIN"] =  ASIN(close)',
'ATAN' : 'df["ATAN"] =  ATAN(close)',
'CEIL' : 'df["CEIL"] =  CEIL(close)',
'COS' : 'df["COS"] =  COS(close)',
'COSH' : 'df["COSH"] =  COSH(close)',
'EXP' : 'df["EXP"] =  EXP(close)',
'FLOOR' : 'df["FLOOR"] =  FLOOR(close)',
'LN' : 'df["LN"] =  LN(close)',
'LOG10' : 'df["LOG10"] =  LOG10(close)',
'SIN' : 'df["SIN"] =  SIN(close)',
'SINH' : 'df["SINH"] =  SINH(close)',
'SQRT' : 'df["SQRT"] =  SQRT(close)',
'TAN' : 'df["TAN"] =  TAN(close)',
'TANH' : 'df["TANH"] =  TANH(close)',
'ADD' : 'df["ADD"] =  ADD(high, low)',
'DIV' : 'df["DIV"] =  DIV(high, low)',
'MAX' : 'df["MAX"] =  MAX(close, timeperiod=30)',
'MAXINDEX' : 'df["MAXINDEX"] =  MAXINDEX(close, timeperiod=30)',
'MIN' : 'df["MIN"] =  MIN(close, timeperiod=30)',
'MININDEX' : 'df["MININDEX"] =  MININDEX(close, timeperiod=30)',
'min, max = MINMAX(close, timeperiod=30)',
'minidx, maxidx = MINMAXINDEX(close, timeperiod=30)',
'MULT' : 'df["MULT"] =  MULT(high, low)',
'SUB' : 'df["SUB"] =  SUB(high, low)',
'SUM' : 'df["SUM"] =  SUM(close, timeperiod=30)
'


indicator_properties = {
    "BBANDS" : { "name": "Bollinger Bands","params" : {"CandlePricePoint" : "close", "timeperiod":5, "nbdevup":2, "nbdevdn":2, "matype":0}},
    "DEMA" : { "name": "Double Exponential Moving Average","params" : {"CandlePricePoint" : "close", "timeperiod":30}},
    "EMA" : { "name": "Exponential Moving Average","params" : {"CandlePricePoint" : "close", "timeperiod":30}},
    "HT_TRENDLINE" : { "name": "Hilbert Transform - Instantaneous Trendline","params" : {"CandlePricePoint" : "close"}},
    "KAMA" : { "name": "Kaufman Adaptive Moving Average","params" : {"CandlePricePoint" : "close", "timeperiod":30}},
    "MA" : { "name": "Moving average","params" : {"CandlePricePoint" : "close", "timeperiod":30, "matype":0}},
    "MAMA": { "name": "MESA Adaptive Moving Average","params" : {"CandlePricePoint" : "close", "fastlimit":0, "slowlimit":0}},
    "MAVP" : { "name": "Moving average with variable period","params" : {"CandlePricePoint" : "close", "periods" : "", "minperiod":2, "maxperiod":30, "matype":0}},
    "MIDPOINT" : { "name": "MidPoint over period","params" : {"CandlePricePoint" : "close", "timeperiod":14}},
    "MIDPRICE" : { "name": "Midpoint Price over period","params" : {"CandleHigh" : "high", "CandleLow" : "low", "timeperiod":14}},
    "SAR" : { "name": "Parabolic SAR","params" : {"CandleHigh" : "high", "CandleLow" : "low", "acceleration":0, "maximum":0}},
    "SAREXT" : { "name": "Parabolic SAR - Extended","params" : {"CandleHigh" : "high", "CandleLow" : "low", "startvalue":0, "offsetonreverse":0, "accelerationinitlong":0, "accelerationlong":0, "accelerationmaxlong":0, "accelerationinitshort":0, "accelerationshort":0, "accelerationmaxshort":0}},
    "SMA" : { "name": "Simple Moving Average","params" : {"CandlePricePoint" : "close", "timeperiod":30}},
    "T3" : { "name": "Triple Exponential Moving Average","params" : {"CandlePricePoint" : "close", "timeperiod":5, "vfactor":0}},
    "TEMA" : { "name": "Triple Exponential Moving Average","params" : {"CandlePricePoint" : "close", "timeperiod":30}},
    "TRIMA" : { "name": "Triangular Moving Average","params" : {"CandlePricePoint" : "close", "timeperiod":30}},
    "WMA" : { "name": "Weighted Moving Average","params" : {"CandlePricePoint" : "close", "timeperiod":30}},

    "ADX" : { "name": "Average Directional Movement Index","params" : {"CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "timeperiod":14}},
    "ADXR" : { "name": "Average Directional Movement Index Rating","params" : {"CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "timeperiod":14}},
    "APO" : { "name": "Absolute Price Oscillator","params" : {"CandlePricePoint" : "close", "fastperiod":12, "slowperiod":26, "matype":0}},
    "AROON" : { "name": "Aroon","params" : {"CandleHigh" : "high", "CandleLow" : "low", "timeperiod":14}},
    "AROONOSC" : { "name": "Aroon Oscillator","params" : {"CandleHigh" : "high", "CandleLow" : "low", "timeperiod":14}},
    "BOP" : { "name": "Balance Of Power","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CCI" : { "name": "Commodity Channel Index","params" : {"CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "timeperiod":14}},
    "CMO" : { "name": "Chande Momentum Oscillator","params" : {"CandlePricePoint" : "close", "timeperiod":14}},
    "DX" : { "name": "Directional Movement Index","params" : {"CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "timeperiod":14}},
    "MACD" : { "name": "Moving Average Convergence/Divergence","params" : {"CandlePricePoint" : "close", "fastperiod":12, "slowperiod":26, "signalperiod":9}},
    "MACDEXT" : { "name": "MACD with controllable MA type","params" : {"CandlePricePoint" : "close", "fastperiod":12, "fastmatype":0, "slowperiod":26, "slowmatype":0, "signalperiod":9, "signalmatype":0}},
    "MACDFIX" : { "name": "Moving Average Convergence/Divergence Fix 12/26","params" : {"CandlePricePoint" : "close", "signalperiod":9}},
    "MFI" : { "name": "Money Flow Index","params" : {"CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "volume" : "", "timeperiod":14}},
    "MINUS_DI" : { "name": "Minus Directional Indicator","params" : {"CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "timeperiod":14}},
    "MINUS_DM" : { "name": "Minus Directional Movement","params" : {"CandleHigh" : "high", "CandleLow" : "low", "timeperiod":14}},
    "MOM" : { "name": "Momentum","params" : {"CandlePricePoint" : "close", "timeperiod":10}},
    "PLUS_DI" : { "name": "Plus Directional Indicator","params" : {"CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "timeperiod":14}},
    "PLUS_DM" : { "name": "Plus Directional Movement","params" : {"CandleHigh" : "high", "CandleLow" : "low", "timeperiod":14}},
    "PPO" : { "name": "Percentage Price Oscillator","params" : {"CandlePricePoint" : "close", "fastperiod":12, "slowperiod":26, "matype":0}},
    "ROC" : { "name": "Rate of change : ((price/prevPrice)-1)*100","params" : {"CandlePricePoint" : "close", "timeperiod":10}},
    "ROCP" : { "name": "Rate of change Percentage: (price-prevPrice)/prevPrice","params" : {"CandlePricePoint" : "close", "timeperiod":10}},
    "ROCR" : { "name": "Rate of change ratio: (price/prevPrice)","params" : {"CandlePricePoint" : "close", "timeperiod":10}},
    "ROCR100" : { "name": "Rate of change ratio 100 scale: (price/prevPrice)*100","params" : {"CandlePricePoint" : "close", "timeperiod":10}},
    "RSI" : { "name": "Relative Strength Index","params" : {"CandlePricePoint" : "close", "timeperiod":14}},
    "STOCH" : { "name": "Stochastic","params" : {"CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "fastk_period":5, "slowk_period":3, "slowk_matype":0, "slowd_period":3, "slowd_matype":0}},
    "STOCHF" : { "name": "Stochastic Fast","params" : {"CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "fastk_period":5, "fastd_period":3, "fastd_""matype":0}},
    "STOCHRSI" : { "name": "Stochastic Relative Strength Index","params" : {"CandlePricePoint" : "close", "timeperiod":14, "fastk_period":5, "fastd_period":3, "fastd_""matype":0}},
    "TRIX" : { "name": "1-day Rate-Of-Change (ROC) of a Triple Smooth EMA","params" : {"CandlePricePoint" : "close", "timeperiod":30}},
    "ULTOSC" : { "name": "Ultimate Oscillator","params" : {"CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "timeperiod1":7, "timeperiod2":14, "timeperiod3":28}},
    "WILLR" : { "name": "Williams' %R","params" : {"CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "timeperiod":14}},

    "AD" : { "name": "Chaikin A/D Line","params" : {"CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "volume" : ""}},
    "ADOSC" : { "name": "Chaikin A/D Oscillator","params" : {"CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "volume" : "", "fastperiod":3, "slowperiod":10}},
    "OBV" : { "name": "On Balance Volume","params" : {"CandlePricePoint" : "close", "volume" : ""}},

    "ATR" : { "name": "Average True Range","params" : {"CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "timeperiod":14}},
    "NATR" : { "name": "Normalized Average True Range","params" : {"CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "timeperiod":14}},
    "TRANGE" : { "name": "True Range","params" : {"CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},

    "AVGPRICE" : { "name": "Average Price","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "MEDPRICE" : { "name": "Median Price","params" : {"CandleHigh" : "high", "CandleLow" : "low"}},
    "TYPPRICE" : { "name": "Typical Price","params" : {"CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "WCLPRICE" : { "name": "Weighted Close Price","params" : {"CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},

    "HT_DCPERIOD" : { "name": "Hilbert Transform - Dominant Cycle Period","params" : {"CandlePricePoint" : "close"}},
    "HT_DCPHASE" : { "name": "Hilbert Transform - Dominant Cycle Phase","params" : {"CandlePricePoint" : "close"}},
    "HT_PHASOR" : { "name": "Hilbert Transform - Phasor Components","params" : {"CandlePricePoint" : "close"}},
    "HT_SINE" : { "name": "Hilbert Transform - SineWave","params" : {"CandlePricePoint" : "close"}},
    "HT_TRENDMODE" : { "name": "Hilbert Transform - Trend vs Cycle Mode","params" : {"CandlePricePoint" : "close"}},


    "CDL2CROWS" : { "name": "Two Crows","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDL3BLACKCROWS" : { "name": "Three Black Crows","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDL3INSIDE" : { "name": "Three Inside Up/Down","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDL3LINESTRIKE" : { "name": "Three-Line Strike","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDL3OUTSIDE" : { "name": "Three Outside Up/Down","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDL3STARSINSOUTH" : { "name": "Three Stars In The South","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDL3WHITESOLDIERS" : { "name": "Three Advancing White Soldiers","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLABANDONEDBABY" : { "name": "Abandoned Baby","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "penetration":0}},
    "CDLADVANCEBLOCK" : { "name": "Advance Block","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLBELTHOLD" : { "name": "Belt-hold","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLBREAKAWAY" : { "name": "Breakaway","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLCLOSINGMARUBOZU" : { "name": "Closing Marubozu","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLCONCEALBABYSWALL" : { "name": "Concealing Baby Swallow","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLCOUNTERATTACK" : { "name": "Counterattack","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLDARKCLOUDCOVER" : { "name": "Dark Cloud Cover","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "penetration":0}},
    "CDLDOJI" : { "name": "Doji","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLDOJISTAR" : { "name": "Doji Star","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLDRAGONFLYDOJI" : { "name": "Dragonfly Doji","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLENGULFING" : { "name": "Engulfing Pattern","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLEVENINGDOJISTAR" : { "name": "Evening Doji Star","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "penetration":0}},
    "CDLEVENINGSTAR" : { "name": "Evening Star","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "penetration":0}},
    "CDLGAPSIDESIDEWHITE" : { "name": "Up/Down-gap side-by-side white lines","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLGRAVESTONEDOJI" : { "name": "Gravestone Doji","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLHAMMER" : { "name": "Hammer","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLHANGINGMAN" : { "name": "Hanging Man","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLHARAMI" : { "name": "Harami Pattern","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLHARAMICROSS" : { "name": "Harami Cross Pattern","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLHIGHWAVE" : { "name": "High-Wave Candle","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLHIKKAKE" : { "name": "Hikkake Pattern","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLHIKKAKEMOD" : { "name": "Modified Hikkake Pattern","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLHOMINGPIGEON" : { "name": "Homing Pigeon","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLIDENTICAL3CROWS" : { "name": "Identical Three Crows","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLINNECK" : { "name": "In-Neck Pattern","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLINVERTEDHAMMER" : { "name": "Inverted Hammer","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLKICKING" : { "name": "Kicking","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLKICKINGBYLENGTH" : { "name": "Kicking - bull/bear determined by the longer marubozu","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLLADDERBOTTOM" : { "name": "Ladder Bottom","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLLONGLEGGEDDOJI" : { "name": "Long Legged Doji","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLLONGLINE" : { "name": "Long Line Candle","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLMARUBOZU" : { "name": "Marubozu","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLMATCHINGLOW" : { "name": "Matching Low","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLMATHOLD" : { "name": "Mat Hold","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "penetration":0}},
    "CDLMORNINGDOJISTAR" : { "name": "Morning Doji Star","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "penetration":0}},
    "CDLMORNINGSTAR" : { "name": "Morning Star","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close", "penetration":0}},
    "CDLONNECK" : { "name": "On-Neck Pattern","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLPIERCING" : { "name": "Piercing Pattern","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLRICKSHAWMAN" : { "name": "Rickshaw Man","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLRISEFALL3METHODS" : { "name": "Rising/Falling Three Methods","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLSEPARATINGLINES" : { "name": "Separating Lines","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLSHOOTINGSTAR" : { "name": "Shooting Star","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLSHORTLINE" : { "name": "Short Line Candle","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLSPINNINGTOP" : { "name": "Spinning Top","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLSTALLEDPATTERN" : { "name": "Stalled Pattern","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLSTICKSANDWICH" : { "name": "Stick Sandwich","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLTAKURI" : { "name": "Takuri (Dragonfly Doji with very long lower shadow)","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLTASUKIGAP" : { "name": "Tasuki Gap","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLTHRUSTING" : { "name": "Thrusting Pattern","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLTRISTAR" : { "name": "Tristar Pattern","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLUNIQUE3RIVER" : { "name": "Unique 3 River","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLUPSIDEGAP2CROWS" : { "name": "Upside Gap Two Crows","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},
    "CDLXSIDEGAP3METHODS" : { "name": "Upside/Downside Gap Three Methods","params" : {"CandleOpen" : "Open", "CandleHigh" : "high", "CandleLow" : "low","CandleClose" : "close"}},

    "BETA" : { "name": "Beta","params" : {"CandleHigh" : "high", "CandleLow" : "low", "timeperiod":5}},
    "CORREL" : { "name": "Pearson's Correlation Coefficient (r)","params" : {"CandleHigh" : "high", "CandleLow" : "low", "timeperiod":30}},
    "LINEARREG" : { "name": "Linear Regression","params" : {"CandlePricePoint" : "close", "timeperiod":14}},
    "LINEARREG_ANGLE" : { "name": "Linear Regression Angle","params" : {"CandlePricePoint" : "close", "timeperiod":14}},
    "LINEARREG_INTERCEPT" : { "name": "Linear Regression Intercept","params" : {"CandlePricePoint" : "close", "timeperiod":14}},
    "LINEARREG_SLOPE" : { "name": "Linear Regression Slope","params" : {"CandlePricePoint" : "close", "timeperiod":14}},
    "STDDEV" : { "name": "Standard Deviation","params" : {"CandlePricePoint" : "close", "timeperiod":5, "nbdev":1}},
    "TSF" : { "name": "Time Series Forecast","params" : {"CandlePricePoint" : "close", "timeperiod":14}},
    "VAR" : { "name": "Variance","params" : {"CandlePricePoint" : "close", "timeperiod":5, "nbdev":1}},

    "ACOS" : { "name": "Vector Trigonometric ACos","params" : {"CandlePricePoint" : "close"}},
    "ASIN" : { "name": "Vector Trigonometric ASin","params" : {"CandlePricePoint" : "close"}},
    "ATAN" : { "name": "Vector Trigonometric ATan","params" : {"CandlePricePoint" : "close"}},
    "CEIL" : { "name": "Vector Ceil","params" : {"CandlePricePoint" : "close"}},
    "COS" : { "name": "Vector Trigonometric Cos","params" : {"CandlePricePoint" : "close"}},
    "COSH" : { "name": "Vector Trigonometric Cosh","params" : {"CandlePricePoint" : "close"}},
    "EXP" : { "name": "Vector Arithmetic Exp","params" : {"CandlePricePoint" : "close"}},
    "FLOOR" : { "name": "Vector Floor","params" : {"CandlePricePoint" : "close"}},
    "LN" : { "name": "Vector Log Natural","params" : {"CandlePricePoint" : "close"}},
    "LOG10" : { "name": "Vector Log10","params" : {"CandlePricePoint" : "close"}},
    "SIN" : { "name": "Vector Trigonometric Sin","params" : {"CandlePricePoint" : "close"}},
    "SINH" : { "name": "Vector Trigonometric Sinh","params" : {"CandlePricePoint" : "close"}},
    "SQRT" : { "name": "Vector Square Root","params" : {"CandlePricePoint" : "close"}},
    "TAN" : { "name": "Vector Trigonometric Tan","params" : {"CandlePricePoint" : "close"}},
    "TANH" : { "name": "Vector Trigonometric Tanh","params" : {"CandlePricePoint" : "close"}},

    "ADD" : { "name": "Vector Arithmetic Add","params" : {"CandleHigh" : "high", "CandleLow" : "low"}},
    "DIV" : { "name": "Vector Arithmetic Div","params" : {"CandleHigh" : "high", "CandleLow" : "low"}},
    "MAX" : { "name": "Highest value over a specified period","params" : {"CandlePricePoint" : "close", "timeperiod":30}},
    "MAXINDEX" : { "name": "Index of highest value over a specified period","params" : {"CandlePricePoint" : "close", "timeperiod":30}},
    "MIN" : { "name": "Lowest value over a specified period","params" : {"CandlePricePoint" : "close", "timeperiod":30}},
    "MININDEX" : { "name": "Index of lowest value over a specified period","params" : {"CandlePricePoint" : "close", "timeperiod":30}},
    "MINMAX" : { "name": "Lowest and highest values over a specified period","params" : {"CandlePricePoint" : "close", "timeperiod":30}},
    "MINMAXINDEX" : { "name": "Indexes of lowest and highest values over a specified period","params" : {"CandlePricePoint" : "close", "timeperiod":30}},
    "MULT" : { "name": "Vector Arithmetic Mult","params" : {"CandleHigh" : "high", "CandleLow" : "low"}},
    "SUB" : { "name": "Vector Arithmetic Substraction","params" : {"CandleHigh" : "high", "CandleLow" : "low"}},
    "SUM" : { "name": "Summation","params" : {"CandlePricePoint" : "close", "timeperiod":30}}
}
